services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  carepaws:
    build: ./carepaws/CarePaws
    container_name: carepaws
    ports:
      - "8082:8081"  # Bahar se 8082 hit karein, ye andar 8081 (Tomcat) par bhejega
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m  # RAM limit set ki hai
      - EUREKA_CLIENT_ENABLED=false   # Eureka bypass kiya taaki jaldi start ho
    restart: unless-stopped

  # Note: Baaki services ko abhi band rakhein taaki RAM crash na ho.
