# server: 
#   port: 8761

# spring:
#   application:
#     name: eureka-server

# eureka:
#   client:
#     register-with-eureka: false
#     fetch-registry: false

server:
  port: 8761

eureka:
  instance:
    # AWS ki Public IP ya Private IP yahan mention karein
    hostname: 13.60.184.171
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://13.60.184.171:8761/eureka/
  server:
    # Replication timeout errors ko rokne ke liye
    peer-node-read-timeout-ms: 5000
    enable-self-preservation: true
