spring:
  application:
    name: CAREPAWS-NGO-SERVICE


  data:
    mongodb:
      uri: mongodb+srv://rastogimanas329:Ys54a4sUZbZpCxhP@cluster0.vl8euvm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: carepaws-ngo-service

internal:
  service:
    token: INTERNAl-NGO-AND-MUNICIPAL-SERVICE-TOKEN

management:
  endpoints:
  web:
  exposure:
  include: health,info


  eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    defaultZone: http://localhost:8761/eureka



resilience4j:
    retry:
      instances:
        ngoRetry:
          maxAttempts: 3
          waitDuration: 300ms

circuitbreaker:
      instances:
        ngoCB:
          failureRateThreshold: 50
          slidingWindowSize: 10
          minimumNumberOfCalls: 5
          waitDurationInOpenState: 15s
