server:
  port: 8084

spring:
  application:
    name: CAREPAWS-MUNCIPAL-SERVICE

  data:
    mongodb:
      uri: mongodb+srv://rastogimanas329:Ys54a4sUZbZpCxhP@cluster0.vl8euvm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: carepaws-muncipal-service

internal:
  service:
    token: INTERNAl-NGO-AND-MUNICIPAL-SERVICE-TOKEN

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

resilience4j:
  retry:
    instances:
      muncipalRetry:
        maxAttempts: 3
        waitDuration: 300ms

  circuitbreaker:
    instances:
      muncipalCB:
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 15s
