#server:
#  port: 8086
#
#spring:
#  application:
#    name: CAREPAWS-NOTIFICATION-SERVICE
#
#
#  data:
#    mongodb:
#      uri: mongodb+srv://rastogimanas329:Ys54a4sUZbZpCxhP@cluster0.vl8euvm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#      database: carepaws-notification-service
#
#internal:
#  service:
#    token: INTERNAl-NGO-AND-MUNICIPAL-SERVICE-TOKEN
#
#  eureka:
#    client:
#      register-with-eureka: true
#      fetch-registry: true
#      service-url:
#        defaultZone: http://localhost:8761/eureka



server:
  port: 8086

spring:
  application:
    name: CarePaws-Notification-Service

  data:
    mongodb:
      uri: mongodb+srv://rastogimanas329:Ys54a4sUZbZpCxhP@cluster0.vl8euvm.mongodb.net/carepaws-municipal-service?retryWrites=true&w=majority
      database: carepaws-notification

internal:
  service:
    token: INTERNAl-NGO-AND-MUNICIPAL-SERVICE-TOKEN

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
